Sketch of standardized POM
jenkinsci/github-checks-plugin pull request #307
Opened 2022-12-16 00:05 UTC by jglick

Wanted to try consuming https://github.com/jenkinsci/scm-api-plugin/pull/180 but that first requires having basic dependencies be reasonably up to date, which they are not. The amount of technical debt in this otherwise smallish plugin is appalling, because of the inheritance of nonstandard idioms from the `analysis-*` universe. Currently stuck on something related to JUnit 5. https://github.com/jenkinsci/bom/pull/1521#issuecomment-1339717547

2022-12-16 00:26 UTC, jglick commented
https://github.com/jenkinsci/plugin-util-api-plugin/blob/00a7b80b6fb464da24eeff8d984ccf20a641cc12/src/test/java/io/jenkins/plugins/util/IntegrationTest.java#L51 is causing all sorts of errors. Should not be using this dep at all.

2022-12-16 00:33 UTC, jglick commented on src/test/java/io/jenkins/plugins/checks/ArchitectureTest.java
> -    static final ArchRule NO_JENKINS_INSTANCE_CALL = PluginArchitectureRules.NO_JENKINS_INSTANCE_CALL;
Whatever this stuff was doing, it can presumably be dropped without anyone noticing.

2022-12-16 00:33 UTC, jglick commented on src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherITest.java
> -public class GitHubChecksPublisherITest extends IntegrationTestWithJenkinsPerTest {
This `IntegrationTestWithJenkinsPerTest` is the problem. Should be rewritten to use just stuff provided by `jenkins-test-harness`.

2022-12-16 00:33 UTC, jglick commented on src/test/java/io/jenkins/plugins/checks/github/GitSCMChecksContextITest.java
> -        WorkflowJob job = createPipeline();
Here for example. What is wrong with the usual `r.createProject(WorkflowJob.class)`?

2022-12-16 00:33 UTC, jglick commented on src/test/java/io/jenkins/plugins/checks/github/status/GitHubSCMSourceStatusChecksTraitTest.java
> -import static io.jenkins.plugins.util.assertions.Assertions.assertThat;
A custom version of `assertThat`?? Just use Hamcrest.

2023-04-14 15:38 UTC, jglick commented
@timja any advice here?

2023-04-14 15:50 UTC, timja commented on pom.xml
> +      <dependency> <!-- TODO pending https://github.com/jenkinsci/github-branch-source-plugin/pull/624 -->
released in https://github.com/jenkinsci/github-branch-source-plugin/releases/tag/1701.v00cc8184df93 AFAICT

2023-04-14 15:53 UTC, timja commented
> @timja any advice here?

or is the question more about the deleting of all of the integration tests in the plugin?

2023-04-14 16:10 UTC, jglick commented
> is the question more about the deleting of all of the integration tests in the plugin?

Yeah, that is the only thing I found that would work. Do you have a better idea?

2023-04-17 08:36 UTC, timja commented
> Yeah, that is the only thing I found that would work. Do you have a better idea?

Switch to the default parent pom but leave the `plugin-util-api` dependency? Can drop the architecture test if needed but not sure if we should drop all integration tests...

2023-04-19 07:30 UTC, timja commented
After trying this myself I see that the issue is that plugin-util-api now uses `junit5` for all it's tests.

It would be non-trivial to re-write to junit5 I think.
Likely easier to rewrite to JTH without the plugin-util-api wrapper.

I'll give that a quick go and if that's not something I have time for I'll merge this.

fyi @uhafner

2023-04-19 07:56 UTC, merged

2023-04-19 08:00 UTC, uhafner requested changes
I don't see a problem to switch the parent pom. 

But I don't understand the reasoning for deleting all the valuable tests, degenerating the coverage but such a huge amount:

![Bildschirmfoto 2023-04-19 um 09 47 45](https://user-images.githubusercontent.com/503338/233007351-66bed116-bf72-490a-8885-9a67ecb287c3.png)

This makes absolutely no sense.

2023-04-19 08:02 UTC, uhafner commented
Why are you requesting a review and then merge such a change?

2023-04-19 08:24 UTC, uhafner commented
Shouldn't this be done by the author of this PR?

2023-04-19 11:15 UTC, timja commented
> Later equals never! 👎

😄 I've made good progress in here:
https://github.com/jenkinsci/github-checks-plugin/pull/332

I found another complexity is that github-branch-source has had some changes which has broken some of the mocking assumptions in this plugin.

I've fixed all but one test in that test class and just need to do some debugging to finish it off. Hopefully other tests will be straightforward to port.